#!/usr/bin/env bash
# Build EISS-website-documentation.pdf from documentation.html.
#
# Adapted from the NetSec sister repository's docs/pdf/build.sh. The one
# structural difference: EISS pages are generated by Eleventy, so
# --shots builds the site into _site/ and serves that, where NetSec
# serves its working tree as is.
#
# Pipeline:
#   1. Optionally refresh the site screenshots: build the site, serve
#      _site/ locally, capture each page with headless Chrome at device
#      scale 1, convert to JPEG at quality 90.
#   2. Headless Chrome renders documentation.html to A4 PDF, with a long
#      --virtual-time-budget so Mermaid finishes drawing every diagram
#      before the print snapshot.
#
# Usage:
#   ./build.sh             # rebuild the PDF only
#   ./build.sh --shots     # also refresh the site screenshots
#
# Requires:
#   - macOS with Google Chrome.app installed
#   - node + npm (for the Eleventy build, --shots only)
#   - python3 with Pillow (for the local server and JPEG conversion,
#     --shots only)

set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$HERE/../.." && pwd)"
CHROME="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
PORT=8766

if [[ ! -x "$CHROME" ]]; then
  echo "Google Chrome.app not found at $CHROME. Install it or edit this script." >&2
  exit 1
fi

# Optional: refresh screenshots ------------------------------------------
if [[ "${1-}" == "--shots" ]]; then
  echo "→ Building the site into _site/"
  ( cd "$REPO_ROOT" && npx @11ty/eleventy --quiet )

  echo "→ Refreshing screenshots"
  ( cd "$REPO_ROOT/_site" && python3 -m http.server $PORT --bind 127.0.0.1 ) >/tmp/eiss-pdf-srv.log 2>&1 &
  SRV=$!
  trap 'kill $SRV 2>/dev/null || true' EXIT
  sleep 1
  # label:path. The Atlas (/anthology-atlas.html) is left out: it renders
  # blank in headless capture, so the Anthology landing page stands in.
  for page in home:index.html conference:2026.html board:board.html anthology:anthology.html roadmap:roadmap.html blog:blog.html; do
    label="${page%%:*}"
    path="${page#*:}"
    # A tall window so reveal-on-scroll sections are inside the viewport
    # at first paint. Scale factor 1 keeps the capture at 1280 logical
    # pixels: at a Mac's DPR 2 each figure is 16 megapixels, which is how
    # the NetSec PDF reached 24.6 MB (netsec.github.io#1727).
    # preferredColorScheme=1 forces the light theme: a fresh headless
    # profile otherwise follows the Mac's own dark setting.
    "$CHROME" --headless --no-sandbox --disable-gpu \
      --window-size=1280,3200 --hide-scrollbars \
      --force-device-scale-factor=1 \
      --blink-settings=preferredColorScheme=1 \
      --virtual-time-budget=12000 \
      --screenshot="$HERE/snap-$label.png" \
      "http://127.0.0.1:$PORT/$path" 2>/dev/null
    python3 - "$HERE/snap-$label" <<'CONVERT'
import sys
from PIL import Image
stem = sys.argv[1]
with Image.open(f"{stem}.png") as im:
    im.convert("RGB").save(f"{stem}.jpg", "JPEG", quality=90,
                           optimize=True, progressive=True)
CONVERT
    rm -f "$HERE/snap-$label.png"
    echo "   $HERE/snap-$label.jpg"
  done
  kill $SRV 2>/dev/null || true
  trap - EXIT
fi

# Build the PDF -----------------------------------------------------------
echo "→ Building EISS-website-documentation.pdf"
"$CHROME" --headless --no-sandbox --disable-gpu --hide-scrollbars \
  --no-pdf-header-footer \
  --virtual-time-budget=30000 \
  --print-to-pdf="$HERE/EISS-website-documentation.pdf" \
  "file://$HERE/documentation.html" 2>&1 | grep -E '(written|ERROR)' || true

ls -lh "$HERE/EISS-website-documentation.pdf"
echo "✓ Done."
