module.exports = [
  {
    title: "Defense Cooperation and Military Assistance",
    chair: "Chair: Niccolò Petrelli, Roma Tre University",
    description: "For nearly all states, various forms of defense cooperation and military assistance are central to their national security policies. This can take the form of bilateral and multilateral arrangements, or of more structured and institutional cooperation through organizations such as the African Union, the EU, NATO or the Association of Southeast Asian Nations. In recent years, there has been a proliferation of various forms of defense cooperation or military assistance, often on a regional or sub-regional level. It can also take a variety of forms, from joint military training and exercises to operational planning, procurement and defense-industrial research. This panel invites papers on defense cooperation and military assistance in a broad and inclusive sense, from a variety of disciplines (history, political science, sociology, etc.) and of analytical, theoretical and empirical perspectives. Papers may cover: responses to traditional security threats (Russia's military assertiveness or China's rise, etc.), or more diffuse risks and challenges (terrorism, proliferation, migration, human smuggling and the impact of global climate change). Papers may also cover the creation and evolution of defense institutions, cooperation arrangements whether in bi-, tri-, or 'minilateral' ways and last but not least, the organizational and operational aspects of innovation within the context of defense cooperation.",
  },
  {
    title: "Military Technology",
    chair: "Chair: Marc DeVore, University of St Andrews",
    description: "This panel addresses the interaction between global security, conflict and technology. Recent technological advances in diverse domains ranging from uninhabited and autonomous systems, robotics to cyber malware, and artificial intelligence and quantum computing are on the verge of transforming the use of force. Technology has also empowered a novel set of actors with an influential role in global security. The dynamics of military innovation, its causes and consequences, are changing. Hence this panel encourages submissions that conceptualize military technologies either as explanandum or as explanans. Preference will be given to those papers that link a systematic understanding of technologies with fundamental questions in International Relations, such as cooperation and conflict, balance of power and hegemony, or continuity and change. This call is explicitly open to diverse disciplines (political science, sociology, history) and welcomes different theoretical orientations, since the panel primarily aims to encourage dialogue between scholars with a substantive interest in the interaction between politics and technologies.",
  },
  {
    title: "Private Actors, Armed Conflict and the State",
    chair: "Chair: Chiara Ruffa, Swedish Defense University",
    description: "In today's political, moral, legal and strategic debates private actors in war are commonly seen as a relic from the pre-Westphalian past that has increasingly returned after the end of the Cold War. A proliferation of private actors such as mercenaries and private security companies, but also insurgents, terrorists, local militias and rebels has been identified as the main source of the state's loss of the monopoly over the use of armed force. The panel aims to explore the complex links and interactions that exist between both spheres at both transnational and national levels. It intends to address the following questions: Why do states choose to collaborate with and support private actors in armed conflicts? How have public-private partnerships in armed conflict evolved historically? How do private actors' and states' strategic agendas align, and what happens if they don't? What moral and legal challenges do public-private partnerships in the realm of armed conflict hold? How do they impact on democratic accountability? The panel welcomes a wealth of diverse theoretical and methodological approaches on different aspects of the connections between public and private spheres in international security.",
  },
  {
    title: "Military Interventions",
    chair: "Chair: Kirsten Harkness, University of St Andrews",
    description: "With the winding down of large-scale boots-on-the-ground multinational missions in Afghanistan and Iraq, it has become apparent in both policy and academic circles that large-scale military interventions are but one option among others. Many other kinds of military interventions have been and are being launched and implemented, ranging from military assistance, to more 'agile' counterinsurgency, drone fighting, peacekeeping, and aerial interventions, among others. Recent work has investigated the politics of forming multinational coalitions for launching military interventions. Other contributions have explored the politics of implementation, looking at caveats and actual behavior of troops on the ground. A third strand has explored the implication of military interventions for the civil-military relations of the home country when those soldiers return home. Notwithstanding recent advances, within the field of security studies, there is little clarity about the conceptual, theoretical and empirical underpinnings of different kinds of military interventions with important implications for both scholarship and policy. This panel welcomes contributions on different types of military interventions and potential comparisons. Contributions are welcome from a variety of disciplines (history, political science, sociology, etc.) and may shed light on conceptual, theoretical and empirical aspects of the ongoing debate on military interventions within the security studies debate in dialogue with other neighboring fields such as peace and conflict research, operation research and military sociology.",
  },
  {
    title: "Terrorism and Counter-Terrorism",
    chair: "Chair: Bernhard Blumenau, University of St Andrews",
    description: "The topics of terrorism and counter/anti-terrorism have in recent years received a huge amount of scholarly attention. The increase in scholarship led to deeper knowledge of and insights into the causes, processes, activities, and ends of as well as responses to terrorist struggles. There is a certain temptation to write studies that summarize existing knowledge, rather than producing innovative, original and/or empirical contributions. There are challenges both in regard to the consistency of the scholarly base and the content of contributions. First, there is a lack of a solid and consistent base of scholarship, due to lack of long-term funding, and difficulty to access primary, empirical data. Second, the field is somewhat obsessed with fashions and topical studies. There is a deep-rooted lack of appreciation of the history of (counter/anti)-terrorism and of case studies that are not in the constant spotlight of media and political attention. At the same time, scholarship has devoted much time and effort to a few main lines of enquiry (e.g. definitions, the 'root causes' discussion, radicalization and de-radicalization, WMD and terrorism, AQ/ISIL). Meanwhile, on the theoretical level, the establishment of Critical Terrorism Studies has created a welcome diversity. However, rather than encouraging exchange, scholars have often resorted to entrenchment in response to this development. This panel is explicitly open to diverse disciplines, such as history, political science, legal studies or sociology. We invite contributions which address any, or possibly all, of the above challenges and which discuss a variety of issues and cases around terrorism and counter/anti-terrorism. This panel intends to offer a multidisciplinary perspective and contribute towards joint research projects.",
  },
  {
    title: "Intelligence",
    chair: "Co-Chairs: Peter Jackson and Damien Van Puyvelde, University of Glasgow",
    description: "Intelligence is deeply embedded within national and transnational security policies and practices. The panel's aim is to understand the various roles intelligence plays at the strategic and tactical level. How do intelligence actors reduce uncertainty and provide a knowledge advantage? And what are the problems and pitfalls? Many intelligence practices challenge legal and ethical boundaries in democratic societies. What kind of structures and mechanisms have been developed to ensure oversight and control of intelligence activities? What role do non-state actors play in the collection, analysis and use of intelligence? We are particularly keen to bring together panellists from various disciplinary backgrounds and with diverse theoretical approaches and methodologies. By comparing and contrasting systems and practices from a range of historical and contemporary cases, as well as state and non-state contexts, the panel aims to provide a rich picture of the current status of Intelligence Studies.",
  },
  {
    title: "Arms Procurement and Transfers",
    chair: "Chair: Jocelyn Mawdsley, Newcastle University",
    description: "The parameters of the global arms trade have changed in the post-Cold War era. Defense firms, especially in the West, have internationalized and some have left or reduced their exposure to the defense sector. There are also new entrants and, as Bitzinger (2010) argues, new arms producing states continue to pursue techno-nationalist policies. These changes have left some existing firms, notably in the overcrowded European market, heavily reliant on exports, which commentators increasingly find ethically problematic. This panel will seek to critically interrogate these developments and their consequences for an environment already trying to deal with disruptive technologies, events and a worsening arms control situation. For this panel, we invite papers that address any of these themes, or related issues. Contributions are welcome from all theoretical approaches and disciplines, and papers that focus on national or multilateral dimensions of arms procurement, transfers, and defense and security industries.",
  },
  {
    title: "WMD Non-Proliferation and Arms Control",
    chair: "Co-Chairs: Kristin Ven Bruusgaard, University of Oslo; Michal Onderco, Erasmus University Rotterdam",
    description: "This panel serves as a platform for presenting and discussing research that adds theoretical depth and empirical breadth to current understanding Weapons of Mass Destruction (WMD), the means of their limitations, as well as strategies of their use in conflict. The central themes to be explored include: 1. the causes and phases of WMD proliferation; 2. nuclear strategy; 3. strategic stability and arms control. To develop a deeper appreciation of the challenges posed by WMD, we encourage participants to answer questions such as: Are we likely to witness a fourth proliferation wave, and if so, when? Are allies of nuclear powers bent on securing their own nuclear deterrents? What changes are the nuclear powers making to their nuclear postures and force structures to strengthen deterrence and what are the consequences? How is the strategic competition between US, Russia and China likely to play out in the nuclear realm? What advantages, if any, does nuclear superiority offer in the event of a crisis or outbreak of war? How will emerging technologies affect the strategic and nuclear competition between great powers or regional nuclear powers? How does public opinion affect nuclear policies, and are public attitudes toward nuclear weapons shifting? What is the role of civil society in managing nuclear risk? The panel seeks to bring together scholars and experts across disciplinary boundaries (e.g. political science, security studies, history, etc.) to discuss these topics, and so, create the space for academic innovation, cross-pollination and policy-relevant work.",
  },
];
